### ISSUE TITLE
Dosen't work on windows

### ISSUE THREAD

**Issue by flamaniac** [twitchax/Sheller#6]
Tests are failing. "CMD" shell is freezing process.

**Comment by twitchax** [comment]
Interesting.  I will take a look.

**Comment by twitchax** [comment]
Ok, I fixed the Windows tests.  I cannot repro issues with `Cmd`.  Do you have a test example that fails?

**Comment by flamaniac** [comment]
I think there is some problem with encoding... Dispate what i set.
https://github.com/jonasmalacofilho/liquidctl

This character cuse problem: ├──

**Comment by twitchax** [comment]
Can you point me to the specific file or line? :)

**Comment by flamaniac** [comment]
It will be hard to reproduce. Try to call "liquidctl status" (i send link before) maybe even without kraken device will return strange utf character. 
Sample output from this exe:

NZXT Kraken X (X42, X52, X62 or X72)
├── Liquid temperature     28.1  °C
├── Fan speed               851  rpm
├── Pump speed             1953  rpm
└── Firmware version      6.0.2  
After calling "liquidctl status" from cmd  process ends and command prompt is normal (exe is session less - not like VIM for example). In different lib I am getting first line of output and encoding error coused by "├" character (but this looks like ascii...)

**Comment by twitchax** [comment]
I just want to see the line of code that you are calling.  I want to see the parameters, etc.

**Comment by flamaniac** [comment]
`
 var echoResult = await  Sheller.Builder
            .UseShell<Cmd>()
            .UseStandardOutputEncoding(Encoding.UTF8)
            .UseStandardErrorEncoding(Encoding.UTF8)
            .UseExecutable("liquidctl.exe")
                .WithArgument("status")
            .ExecuteAsync();
`
It is reciving first line of output: 
![obraz](https://user-images.githubusercontent.com/6348462/74989004-95bbb100-543f-11ea-86de-294b85ce02af.png)

**Comment by twitchax** [comment]
I cannot repro a crash, but it seems that using `.UseStandardOutputEncoding` is not required.

Can you try removing the two output encoding lines?  I don't think they are required for those characters.

**Comment by flamaniac** [comment]
Ok. I have confirmed that this is problem of exe that i am calling (in has Python interpreter and Python Script inside. Sorry for bother
